packages:
  - apps/*
  - packages/*
  - scripts/*

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  bcrypt: true
  esbuild: true
  prisma: true
  sharp: true

minimumReleaseAge: 10080
